### ISSUE TITLE
nano-nginx content

### ISSUE THREAD

**Issue by vincentserpoul** [Zenithar/nano-nginx#2]
Hi, I tried running nano-nginx but no success.
docker run -dit --name testnginx -p 443:443 -p 80:80 zenithar/nano-nginx
>> Exited (0) 3 seconds ago

no logs.

From the repo, it seems your own website conf are included, is it actually the case (I couldn't check as I couldn't run it) ?
If it is, would it make sense to create a virgin/template image and then a small tutorial in the README.md?

**Comment by Zenithar** [comment]
Configuration has to be mounted as a volume (-v).

```
docker run --rm --name nginx -v /srv/http:/www -v /var/log/nginx:/var/log/nginx -v /etc/nginx:/etc/nginx -p 80:80 -p 8443:443 zenithar/nano-nginx:latest
```

It's possible that the embedded configuration does not work, initial image is quite old now ^^

**Comment by vincentserpoul** [comment]
Hmm, I usually embed the conf in my containers, but I guess I can also simply delete the existing one.
That said, I think it would be really interesting if you provide your current working conf, as a reference :).
I actually followed your blog post a while ago and built my own "nano-nginx" with a few other packages, but i feel that it would be better to take yours as "FROM" as it seems you update it frequently ^^.

**Comment by Zenithar** [comment]
Ok, I understand you, I will refresh the default configuration as soon as possible.

**Comment by Zenithar** [comment]
Example usage done, is it what you need ?

**Comment by vincentserpoul** [comment]
:+1:  even better than I expected :)

I will try it in my setup soon to replace mine and contribute back if I have any feedback!

merci beaucoup !
